language: python
before_install:
 - sudo apt-get install -qq lxml2-dev libxslt-dev
python:
  - 2.6
  - 2.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script:
  - python test.py
  - coverage run --source=bdrxml test.py
after_success: coveralls
